language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
before_install:
  - sudo apt-get update -qq
  - sudo ./travis-ci/setup_ldap.sh
  - gem update bundler
  - bundle --version
  - gem update --system
  - gem --version

#cache: bundler
