language: ruby
rvm:
  - 2.0.0
  - 2.1.4
  - 2.1.5
  - 2.2.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install qt5-default libqt5webkit5-dev
  - sudo ./travis-ci/setup_ldap.sh
cache: bundler
